In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
print(a)

[1 2 3]


In [6]:
b = np.array([(1,2,3),(3,45,5)])

In [7]:
print(b)

[[ 1  2  3]
 [ 3 45  5]]


In [8]:
import sys

In [9]:
s =  range(1000)

In [10]:
print(sys.getsizeof(1)*len(s))

28000


In [11]:
d = np.arange(1000)

In [12]:
print(d.size * d.itemsize)
import time

8000


In [15]:
size = 100000
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)
start = time.time()
result = [(x,y) for x,y in zip(list1,list2)]
print((time.time()-start)*1000)
start = time.time()
result = array1+array2
print((time.time()-start)*1000)


54.66580390930176
4.876613616943359


## NumPy operations