In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([(1,2,3),(3,45,5)])

In [5]:
print(b)

[[ 1  2  3]
 [ 3 45  5]]


In [6]:
import sys

In [7]:
s =  range(1000)

In [8]:
print(sys.getsizeof(1)*len(s))

28000


In [9]:
d = np.arange(1000)

In [10]:
print(d.size * d.itemsize)
import time

8000


In [11]:
size = 100000
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)
start = time.time()
result = [(x,y) for x,y in zip(list1,list2)]
print((time.time()-start)*1000)
start = time.time()
result = array1+array2
print((time.time()-start)*1000)


50.9343147277832
5.445718765258789


## NumPy operations

In [22]:
a = np.array([(2,3,4),(4,5,6)])

In [23]:
print(a.ndim)

2


In [24]:
print(a.dtype)

int64


In [25]:
print(a.itemsize)

8


In [26]:
print(a.size)

6


In [27]:
print(a.shape)

(2, 3)


In [30]:
a.reshape(3,2)

array([[2, 3],
       [4, 4],
       [5, 6]])

In [31]:
a[0,2]

4

In [34]:
a = np.linspace(1,3,10)

In [35]:
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [39]:
a = np.array([(2,3,4),(4,5,6)])
print(np.std(a))

1.2909944487358056
